### ISSUE TITLE
iOS Orientation Error

### ISSUE THREAD

**Issue by thiagodelmotte** [appcelerator-modules/ti.barcode#14]
Hy,

I'm using your module for my app, but at iOS it's not changing orientation correctly. See screenshots.

Using iPhone 6 iOS 8.2.
Ti 4.0.0.v20150323131014
Xcode 6.2
ti.barcode 1.9.1

![img_4624](https://cloud.githubusercontent.com/assets/2932550/6908852/e9aa03d0-d716-11e4-97b5-fb2754423f5e.PNG)
![img_4625](https://cloud.githubusercontent.com/assets/2932550/6908851/e9a85bfc-d716-11e4-937d-cd84229b8184.PNG)

**Comment by thiagodelmotte** [comment]
When I changed the device orientation from portrait to landscape, half of the screen gets blackened and the camera gets very weird on the other half, it shows the image in the previous orientation and cropped irregularly.

I've read a topic at stackoverflow saying that this is related to the AVFoundation Live Camera Layer as it does not rotate normally along with the window thus we need to use a CATransform3D in order to rotate properly.

Follows the article: http://stackoverflow.com/questions/9688070/zxing-reader-in-lanscape-mode

**Comment by ygbr** [comment]
+1

**Comment by ingo** [comment]
Hi All--thank you for the research. It will be a little while since we are able to fix this ourselves, but if you are interested in filing a PR, we'd be happy to review and merge it.

**Comment by kosso** [comment]
+1

**Comment by moizchhatriwala** [comment]
Did any body resolve the orientation issues...

**Comment by kosso** [comment]
Hi, Since this issue, I resolved it by using functionality built into iOS since 7.0 which can detect most barcode types. 

See [here](https://developer.apple.com/library/prerelease/ios/documentation/AVFoundation/Reference/AVMetadataMachineReadableCodeObject_Class/index.html#//apple_ref/doc/constant_group/Machine_Readable_Object_Types) for the available code types it can detect. 

So, a long time ago I worked on a fork of a custom camera module, where you can have the camera view on a view of any size. It uses AVCaptureVideoDataOutput to get its image from the camera. 

As it turns out, that exactly where you need to add the setting to activate built-in 2D code detection. 

So, I've added the ability to detect codes to my camera module. 

It's a bit rough around the edges, but does exactly what I need, with no fuss.  https://github.com/kosso/SquareCamera

I haven't made it possible to set which codes it can detect yet, but the list of codes the module can detect can be found on [line 432 here](https://github.com/kosso/SquareCamera/blob/master/Classes/ComMfoggSquarecameraView.m#L432) if you want to re-build the module yourself.  (Also note the frameworks it needs in module.xcconfig).

Hope this helps!

**Comment by AppWerft** [comment]
+1

**Comment by hansemannn** [comment]
This does not seem to be an issue with latest versions anymore.
